### PR TITLE
Bug/yomichan to yomitan

### PR DESCRIPTION
**Pull request by J-O-S-H-L**
Used VSCodes search function to find all instances of Yomichan or yomichan and replace them with Yomitan and yomitan respecively. Only replaced instances where the context of the change was clear. 

I ignored .py and .js files in the search as I didn't want to mess with the code base. Some files (such as yomichantemplates.md) were changed to yomitantemplates.md and the docs/assets/yomichan folder was changed to docs/assets/yomitan. I did my best to make sure that links were not broken when referenced elsewhere.

### CODE REVIEW

**Comment by arbyste** [comment]
Thanks for looking into this! I'll go through and take a look soon. There were a handful of Yomichan occurrences that I wanted to leave as is for historical reasons (some of them were quotes from other people iirc) so I might need to revert some.

**Comment by J-O-S-H-L** [comment]
There were some quotes and I did my best to ignore them but I may have missed some. I did review each change individually so hopefully its not too much of a hassle. Thanks for keeping the project going :)

**Comment by arbyste** [comment]
I'm sorry, I only just got around to looking at this, and it actually looks like none of these changes are actually necessary.

It looks like all the modifications you made were on the master branch. Unfortunately the code base is a bit confusing, and the actual docs that are served online aren't saved in the master branch. The stable version docs are in the branch "temp-master-docs" while the prerelease docs are stored in the "dev" branch. This is the structure that I received from the old owner of the repo, and I haven't modified it.

The "temp-master-docs" branch is ahead of the "master" docs by over a year, so I don't think there's a sensible way that I can merge this PR into the "temp-master-docs" branch.

Thank you for doing this, and I'm sorry you put this work in for nothing. I've updated yomichan references on the "dev" branch, and I'll do it soon on the "temp-master-docs" branch as well.

**Comment by J-O-S-H-L** [comment]
Ahh no worries, I should have paid a bit closer attention. Thanks for mataining this repo!

**Pull request closed without merging**
